### ISSUE TITLE
Having trouble typing resolvePromiseAction()

### ISSUE THREAD

**Issue by chmac** [tomekkleszcz/redux-saga-promise-actions#20]
Firstly, thanks again fro all the help with my last round of issues. Really appreciate it. Also, happy new year!

I've updated to the latest package, and updated typescript to support template literal types. I'm seeing an issue trying to call `resolvePromiseAction()`. The invocation is:

```typescript
resolvePromiseAction(action, response)
```

Then the typing error is:

```
Argument of type '[R]' is not assignable to parameter of type 'R extends undefined ? [] : [R]'.ts(2345)
```

You can see the code in full context [here](https://github.com/GenerousLabs/share/blob/e476c9f692f2f8a9d4dc8b6d8b182cc9e7c3243f/expo/src/utils/saga.utils.ts#L50) if that's helpful.

I think my type is correct, but somehow the `...` spread operator doesn't seem to work. I guess I'm missing something. What would be the correct way to invoke `resolvePromiseAction` in TypeScript? Open to a PR which adds that to the docs?

**Comment by tomekkleszcz** [comment]
Hi, Sorry for the late reply, had a busy week. I've implemented function overload to `resolvePromiseAction` and `rejectPromiseAction` methods. I've checked the changes locally and it seems to resolve your issue. Please take a look at the `bugfix/20` and let me know if the fix is working for you. I will merge the changes to the `master` branch then.

**Comment by chmac** [comment]
@tomekkleszcz Awesome, thanks for the quick fix, the `bugfix/20` branch looks great, works like a charm!

**Comment by tomekkleszcz** [comment]
@chmac Thank you for reporting the bug. I am closing this issue.
